# Generate version.h from git (tags x.y.z or x.y.z-suffix).
# Pass -Configuration "Release" to omit commit hash (clean version for release builds).
# Other configs include hash and build timestamp so builds from the same commit are distinguishable.

param([string]$Configuration = "")

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path
$OutFile = Join-Path $ScriptDir "version.h"
$includeHash = ($Configuration -ne "Release")

Push-Location $RepoRoot
try {
    $describe = $null
    $versionShort = "0.0.0"
    $versionFull = "0.0.0"
    $major = 0
    $minor = 0
    $revision = 0

    try {
        $describe = & git describe --tags --long 2>$null
    } catch {}

    if ($describe -match '^(.+)-(\d+)-g([0-9a-f]+)$') {
        $tag = $Matches[1].TrimStart('v')
        $count = [int]$Matches[2]
        $hash = $Matches[3]
        if ($count -eq 0) {
            $versionShort = $tag
            if ($includeHash) {
                $versionFull = "${tag}.g${hash}"
            } else {
                $versionFull = $tag
            }
        } else {
            $versionShort = "${tag}-dev.${count}"
            if ($includeHash) {
                $versionFull = "${tag}-dev.${count}.g${hash}"
            } else {
                $versionFull = "${tag}-dev.${count}"
            }
        }
    } elseif ($describe) {
        $versionShort = $describe.TrimStart('v')
        $versionFull = $versionShort
    } else {
        $shortHash = & git rev-parse --short HEAD 2>$null
        if ($shortHash) {
            $versionShort = "0.0.0-dev.0"
            $versionFull = if ($includeHash) { "0.0.0-dev.0.g$shortHash" } else { "0.0.0-dev.0" }
        }
    }

    # Non-Release: append build timestamp (UTC) so multiple builds from same commit are distinguishable
    if ($includeHash -and $versionFull) {
        $buildTime = [DateTime]::UtcNow.ToString('yyyyMMddHHmmss')
        $versionFull = "${versionFull}+${buildTime}"
    }

    if ($versionShort -match '^(\d+)\.(\d+)\.(\d+)') {
        $major = [int]$Matches[1]
        $minor = [int]$Matches[2]
        $revision = [int]$Matches[3]
    }

    $escapedShort = $versionShort -replace '\\', '\\\\' -replace '"', '\"'
    $escapedFull = $versionFull -replace '\\', '\\\\' -replace '"', '\"'
    $content = @"
/*
 * Generated by update_version.ps1 - do not edit.
 */

#ifndef __VERSION_H__
#define __VERSION_H__

#define F4WX_VERSION_MAJOR   $major
#define F4WX_VERSION_MINOR   $minor
#define F4WX_VERSION_REVISION $revision
#define F4WX_VERSION         "$escapedShort"
#define F4WX_VERSION_FULL    "$escapedFull"

#endif /* __VERSION_H__ */
"@
    [System.IO.File]::WriteAllText($OutFile, $content, [System.Text.UTF8Encoding]::new($false))
} finally {
    Pop-Location
}
